version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "npm", "run", "dev" ]
    volumes:
      - ./:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: bash -c "/usr/wait-for-it.sh --timeout=0 sense:3036 && node index.js"

  db:
    image: postgres:13
    container_name: sense
    volumes:
      - ./.ignore/postgres/postgres:/var/lib/postgresql/data
    env_file:
      - .env
